### ISSUE TITLE
I see no commit history in this repository 

### ISSUE THREAD

**Issue by Lakshmikanth2001** [ericsia/vscode-python-snippet-pack-2.0#11]
- I am able to see only one commit and having some problem with `fetching upstream` option in my forked repo

**Comment by ericsia** [comment]
> * I am able to see only one commit and having some problem with `fetching upstream` option in my forked repo

@Lakshmikanth2001 I was trying to clean January commit due to too much unnecessary commit done by me previously. I think I accidentally cleaned all yesterday. I think u have to run `git clone` again or maybe refork.
I'm so sorry 😭

**Comment by Lakshmikanth2001** [comment]
No worries I have reforked the repo
