### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by Lakshmikanth2001** [ericsia/vscode-python-snippet-pack-2.0#13]
please enable `Github action` so that we can run our tests every time a particular develpoer makes a pull request

**Comment by ericsia** [comment]
> please enable `Github action` so that we can run our tests every time a particular develpoer makes a pull request

![image](https://user-images.githubusercontent.com/24624808/158791935-fb8e731e-82dc-48f6-90db-3c30dc48e7cb.png)
I wonder why 31%

**Comment by Lakshmikanth2001** [comment]
So first file contain `31%` of total test cases
