### ISSUE TITLE
Improving our `commit` messages 

### ISSUE THREAD

**Issue by Lakshmikanth2001** [ericsia/vscode-python-snippet-pack-2.0#15]
112f9197d4f8fad1174b04e523a75d3f2f6cdc3b there are many commits with the name `Add files via upload` it would really help me in understanding what each `git commit` does so as to improve our project maintainability

**Comment by ericsia** [comment]
I see, because last time I rmb
1. is just adding algo- mysqlpython
2. Remove the dot
So I figure the changes is not significant I didn't add message. I'll add the message next time.
