### ISSUE TITLE
with operations

### ISSUE THREAD

**Issue by shivan-s** [ericsia/vscode-python-snippet-pack-2.0#16]
This is a really cool pack! I love it.

Can we get some snippets for `with` statements please?

```python
with open('blah.txt', 'wb') as f:
   f.write(foo)
```

I would write one but no idea where what type of snippet it would be.

```json
    "with w": {
        "prefix": "with write",
        "body": [
        "with open(file, 'w') as f:",
        "/tf.write(value)",
        ],
        "description": "write a text file"
    },
    "with wb": {
        "prefix": "with write binary",
        "body": [
        "with open(file, 'wb') as f:",
        "/tf.write(value)"
        ],
        "description": "write a binary file"
    },
    "with r": {
        "prefix": "with read",
        "body": [
        "with open(file, 'r') as f:",
        "/ttext = f.read()"
        ],
        "description": "read a text file"
    },
    "with rb": {
        "prefix": "with read binary",
        "body": [
        "with open(file, 'rb') as f:",
        "/tfile_read = f.read()"
        ],
        "description": "read a binary file"
    }
```
Thanks in advance.

**Comment by ericsia** [comment]
> This is a really cool pack! I love it.
> 
> Can we get some snippets for `with` statements please?
> 
> ```python
> with open('blah.txt', 'wb') as f:
>    f.write(foo)
> ```
> 
> I would write one but no idea where what type of snippet it would be.
> 
> ```json
>     "with w": {
>         "prefix": "with write",
>         "body": [
>         "with open(file, 'w') as f:",
>         "/tf.write(value)",
>         ],
>         "description": "write a text file"
>     },
>     "with wb": {
>         "prefix": "with write binary",
>         "body": [
>         "with open(file, 'wb') as f:",
>         "/tf.write(value)"
>         ],
>         "description": "write a binary file"
>     },
>     "with r": {
>         "prefix": "with read",
>         "body": [
>         "with open(file, 'r') as f:",
>         "/ttext = f.read()"
>         ],
>         "description": "read a text file"
>     },
>     "with rb": {
>         "prefix": "with read binary",
>         "body": [
>         "with open(file, 'rb') as f:",
>         "/tfile_read = f.read()"
>         ],
>         "description": "read a binary file"
>     }
> ```
> 
> Thanks in advance.

@ShivanS93 did you mean file operation. Type `file-` see if it matches your preference.
If there is anything you like to add, I am happy to add them.
Currently I notice ReadBinary and WriteBinary missing, can you check is there anything else?

**Comment by shivan-s** [comment]
Apologies. I think this is sufficient! ReadBinary and WriteBinary only involve adding a 'b'. I'll close this issue.
