### ISSUE TITLE
Python Snippets 3 sometimes didn't work

### ISSUE THREAD

**Issue by iknownoth1ng** [ericsia/vscode-python-snippet-pack-2.0#19]
Python Snippets 3:v3.3.17
vscode:1.75.0

failure
![image](https://user-images.githubusercontent.com/54530758/216701581-9cdc06bc-c95a-4895-90cd-50d69d5bc133.png)

successful
![image](https://user-images.githubusercontent.com/54530758/216701409-dc5b7c11-66af-45c4-8e25-9cc624a376cb.png)

**Comment by ericsia** [comment]
> Python Snippets 3:v3.3.17 vscode:1.75.0
> 
> failure ![image](https://user-images.githubusercontent.com/54530758/216701581-9cdc06bc-c95a-4895-90cd-50d69d5bc133.png)
> 
> successful ![image](https://user-images.githubusercontent.com/54530758/216701409-dc5b7c11-66af-45c4-8e25-9cc624a376cb.png)

It is vscode issue not this extension: https://github.com/microsoft/vscode/issues/173408
You can open a new issue + link this extension, let them have a look.
I believe they will take action only is multiple people report them: https://github.com/microsoft/vscode/issues/new/choose
