### ISSUE TITLE
 9024

### ISSUE THREAD

**Issue by Ninja-mann** [ericsia/vscode-python-snippet-pack-2.0#2]
vscode://vscode.github-authentication/did-authenticate?windowid=3&code=b2779303fdffaa372bcb&state=cc34352e-691e-43b6-9e88-feb7ec641714

**Comment by ericsia** [comment]
> vscode://vscode.github-authentication/did-authenticate?windowid=3&code=b2779303fdffaa372bcb&state=cc34352e-691e-43b6-9e88-feb7ec641714

hi, may I know what is the issue you are facing?
Are you using older version of vscode? try upgrade to 1.62.3 above
or
make Chrome your default browser temporarily and sign in again
