### ISSUE TITLE
How to add your own snipped

### ISSUE THREAD

**Issue by livan3li** [ericsia/vscode-python-snippet-pack-2.0#21]
hi, i think questions is clear. I want to add my own snipped. Is this possible?

**Comment by livan3li** [comment]
ok. I figured out. Owner of repo has code snipped creator tool which is [here](https://github.com/ericsia/jsonSnippet). You can write your own rule and need to add snipped to one of the file in this path.

C:\Users\[user name]\.vscode\extensions\ericsia.pythonsnippets3-3.3.18\snippets 

you need to restart the vs-code after adding snipped. 

Here is one i added. 

> "end.region": {
		"prefix": "region",
		"body": "# region ${1:name of region} \n\n# endregion",
		"description": "Creates a region "
	}

**Comment by ericsia** [comment]
> ok. I figured out. Owner of repo has code snipped creator tool which is [here](https://github.com/ericsia/jsonSnippet). You can write your own rule and need to add snipped to one of the file in this path.
> 
> C:\Users[user name].vscode\extensions\ericsia.pythonsnippets3-3.3.18\snippets
> 
> you need to restart the vs-code after adding snipped.
> 
> Here is one i added.
> 
> > "end.region": {
> > "prefix": "region",
> > "body": "# region ${1:name of region} \n\n# endregion",
> > "description": "Creates a region "
> > }

If you add manually like this it will be removed in next update. So if you plan to add your snippet to this package. U can open a pull request, we will consider to add it
