### ISSUE TITLE
Publish on Open VSX registry?

### ISSUE THREAD

**Issue by SleepySomnia** [ericsia/vscode-python-snippet-pack-2.0#23]
This extension should be on the Open VSX registry for open source VS Code binaries such as VSCodium, as they can't access to Visual Studio Marketplace due to licensing issues, as the marketplace is only licensed for official Microsoft builds.

While you can manually download the extension from the Microsoft Extension Marketplace as a .vsix file and install it on VSCodium, and it works without any problems, the downside is that it doesn't get any automatic updates.

I think it should be published on the Open VSX registry for people who use VSCodium, the open-source VSCode binary, instead of the proprietary Microsoft Visual Studio Code, so that the extension gets automatic updates and it's much more convenient that way.

https://open-vsx.org/

**Comment by ericsia** [comment]
> This extension should be on the Open VSX registry for open source VS Code binaries such as VSCodium, as they can't access to Visual Studio Marketplace due to licensing issues, as the marketplace is only licensed for official Microsoft builds.
> 
> While you can manually download the extension from the Microsoft Extension Marketplace as a .vsix file and install it on VSCodium, and it works without any problems, the downside is that it doesn't get any automatic updates.
> 
> I think it should be published on the Open VSX registry for people who use VSCodium, the open-source VSCode binary, instead of the proprietary Microsoft Visual Studio Code, so that the extension gets automatic updates and it's much more convenient that way.
> 
> https://open-vsx.org/

done, thank you~
