### ISSUE TITLE
Typo: `import-seaborn` snippet doesn't match Seaborn's common abbreviation

### ISSUE THREAD

**Issue by vm70** [ericsia/vscode-python-snippet-pack-2.0#25]
Hello,

Thanks for making this VS Code snippet pack, it's really useful! I would just like to point out that the [`seaborn`](https://seaborn.pydata.org/) Python library is usually [imported as `sns`](https://seaborn.pydata.org/faq.html#why-is-seaborn-imported-as-sns). It's an obscure reference to the library's namesake, Samuel Norman Seaborn, as well as a backronym for "seaborn name space".

What do you think about changing it?

**Comment by ericsia** [comment]
> Hello,
> 
> Thanks for making this VS Code snippet pack, it's really useful! I would just like to point out that the [`seaborn`](https://seaborn.pydata.org/) Python library is usually [imported as `sns`](https://seaborn.pydata.org/faq.html#why-is-seaborn-imported-as-sns). It's an obscure reference to the library's namesake, Samuel Norman Seaborn, as well as a backronym for "seaborn name space".
> 
> What do you think about changing it?

@vm70 i don't remember i included seaborn import snippet. I think you've mistaken it

**Comment by vm70** [comment]
@ericsia The Seaborn snippet is on line 555 of `snippets/python_snippets.json`. Would you like me to make a pull request with this commit?

**Comment by ericsia** [comment]
done
