### ISSUE TITLE
how can i open the code preview like the red part?

### ISSUE THREAD

**Issue by leezm1120** [ericsia/vscode-python-snippet-pack-2.0#3]
![1](https://user-images.githubusercontent.com/18046049/151645668-26e57d25-f9c7-41b5-a645-7e0672c91f8d.jpg)
![2](https://user-images.githubusercontent.com/18046049/151645674-46ad039c-3af8-411f-81de-bb7b4bc4982e.png)

**Comment by ericsia** [comment]
Use the Up and Down arrow on your keyboard. If this issue is solved, kindly help to close it~

**Comment by leezm1120** [comment]
Oh, I've solved it. The macOS shortcut is com+I
