### ISSUE TITLE
Linting problom report.

### ISSUE THREAD

**Issue by stnjumu** [ericsia/vscode-python-snippet-pack-2.0#4]
Thank you for your excellent work!
I found this extension has some probloms with the "python" extension.
with python extension opening:
![pythonOpening](https://user-images.githubusercontent.com/39263455/154281675-cd743a64-7565-4fd8-90d6-60f4db0069ad.gif)
with python extension closing:
![pythonClosing](https://user-images.githubusercontent.com/39263455/154283205-14963064-6c57-4d32-8c3c-ba72bab757ee.gif)

and the two extensions:
![3](https://user-images.githubusercontent.com/39263455/154283892-1a43b7e6-3aca-4141-81f1-10654bcb4a91.png)
![4](https://user-images.githubusercontent.com/39263455/154283916-6a7b129b-a174-4557-aa98-5114b5696a06.png)

**Comment by ericsia** [comment]
> Thank you for your excellent work! I found this extension has some probloms with the "python" extension. with python extension opening

This is python extension problem, I have open an issue to them

Meanwhile, you might want to update to this and the keyword is `apply` https://marketplace.visualstudio.com/items?itemName=EricSia.pythonsnippets3

**Comment by ericsia** [comment]
> Thank you for your excellent work! I found this extension has some probloms with the "python" extension. with python extension opening

This is python extension problem, I have open an issue to them to wait their reply.

Meanwhile, you might want to update to this and the keyword is `apply` https://marketplace.visualstudio.com/items?itemName=EricSia.pythonsnippets3 

while if you want to see the example just type `abs` and use your arrow key or scroll down

**Comment by ericsia** [comment]
> Thank you for your excellent work! I found this extension has some probloms with the "python" extension. with python extension opening

This is python extension problem, I have open an issue to them to wait their reply.

Meanwhile, you might want to update to this and the keyword is `apply` https://marketplace.visualstudio.com/items?itemName=EricSia.pythonsnippets3 

while if you want to see the example just type `abs` and use your arrow key or scroll down
I'll push an update to change it to dash if they decided not to fix it after 2 weeks
![image](https://user-images.githubusercontent.com/24624808/154318061-2d4c5d27-58c8-4775-9ae3-067c0bc15588.png)

**Comment by stnjumu** [comment]
> > Thank you for your excellent work! I found this extension has some probloms with the "python" extension. with python extension opening
> 
> This is python extension problem, I have open an issue to them to wait their reply.
> 

1. Thank you for contacting them and wish you can fix this problem.
2. I switch to python snippets 3 extension v3.3.3, but it's different with yours above.
    What should I do to change "." to "-"? Maybe this is a temporary acceptable solution to the problem.
![1](https://user-images.githubusercontent.com/39263455/154400426-0c7cea9f-4788-498e-bcce-a5ed86799eae.png)

**Comment by ericsia** [comment]
> 1. Thank you for contacting them and wish you can fix this problem.
> 2. I switch to python snippets 3 extension v3.3.3, but it's different with yours above.
>    What should I do to change "." to "-"? Maybe this is a temporary acceptable solution to the problem.


If they didn't provide a solution I will change `apply.` become `apply-` let's give them some time to check. Personally I like `.` better.

But for now say if you want to look at `abs` function example 
1. add a `-` behind, for example type `abs-`
Or
2. Type `abs` but use mouse to scroll down to see the example, you can use down arrow also
Or
3. Type `apply` then use mouse or arrow key to scroll down

**Comment by ericsia** [comment]
> 1. Thank you for contacting them and wish you can fix this problem.
> 2. I switch to python snippets 3 extension v3.3.3, but it's different with yours above.
>    What should I do to change "." to "-"? Maybe this is a temporary acceptable solution to the problem.


@stnjumu  If they didn't provide a solution I will change `apply.` become `apply-` let's give them some time to check. Personally I like `.` better.

But for now say if you want to look at `abs` function example 
1. add a `=` behind, for example type `abs=`
Or
2. Type `abs` but use mouse to scroll down until you saw `apply.abs` to see the example, you can use down arrow also
Or
3. Type `apply` then use mouse or arrow key to scroll down until you saw `apply.abs`

**Comment by ericsia** [comment]
> > > Thank you for your excellent work! I found this extension has some probloms with the "python" extension. with python extension opening

@stnjumu I have pushed an update of 3.3.5 to change everything become - so you can type `apply-abs` if you like.
If this is solved please help me to close it, else I will close this issue in 3 days.

**Comment by stnjumu** [comment]
This extension is very useful. I hope more people will know about it.
Have a nice day! ;-)
