### ISSUE TITLE
Please review all the previous pull request from `old repository`

### ISSUE THREAD

**Issue by Lakshmikanth2001** [ericsia/vscode-python-snippet-pack-2.0#5]
Please try to review `6` pull request to the remote repository it will be a great help for the developers how have done some good working for this repository and update the previous extension

**Comment by ericsia** [comment]
> Please try to review `6` pull request to the remote repository it will be a great help for the developers how have done some good working for this repository and update the previous extension

use \t instead of space next time will greatly help.
Regardless, I'll update it in 2 weeks once I finish check I didn't miss anything from 6 branches. 
Btw, thanks

**Comment by ericsia** [comment]
@Lakshmikanth2001 done. I have updated the extension, thanks for your help.
Also please help to rate in [marketplace](https://marketplace.visualstudio.com/items?itemName=EricSia.pythonsnippets3&ssr=false#review-details)
