### ISSUE TITLE
Spliting up `python_snippets.json` into `multiple` json files

### ISSUE THREAD

**Issue by Lakshmikanth2001** [ericsia/vscode-python-snippet-pack-2.0#7]
- I feel python_snippets.json has grown in size it will be hard to maintain if we don't split up this `.json` into smaller files

**Comment by ericsia** [comment]
Noted. Will split them if anyone help to add [those highlight method](https://github.com/ericsia/vscode-python-snippet-pack-2.0/blob/master/CONTRIBUTING.md) in next update

**Comment by ericsia** [comment]
@Lakshmikanth2001 just splitted all of it, sync with the new one

**Comment by ericsia** [comment]
@Lakshmikanth2001 just splitted all of it, sync with the new one.
Thanks for your help again
